name: Build Go Application

on:
  push:
    branches:
      - main  # adjust as per your main branch name
  pull_request:
    branches:
      - main  # adjust as per your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.5'  # adjust to your Go version
        
    - name: Build
      run: go build -o myapp
      
    - name: Test
      run: go test ./...
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build docker image
      run: docker build -t go-web-app:latest .
    - name: login to ocir
      uses: docker/login-action@v3
      id: login-ocir
      with:
         registry: https://hub.docker.com/
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         
     
    - name: Tag docker image
      run: |
         docker tag go-web-app:latest karthikeyudu/go-web-app:$(BUILD_NUBER)       
         
    - name: Push Docker Image to ocir
      run: | 
           docker push karthikeyudu/go-web-app:$(BUILD_NUBER)
